import numpy as np

#first method
print('conversion from other python structures(list,tuples)')
print("\n")
listarray=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(listarray)
print("\n")

print('intrinsic numpy array creation objects(arrange,ones,zeros,etc)')
print("\n")
print("zeros")
zeros=np.zeros((3,3))
print(zeros)
print("\n")
print("arange:")
arange=np.arange(15)
print(arange)
print("\n")
print("linspace:")
linspace=np.linspace(1,5,4)
print(linspace)
print("\n")
print('emp')
emp=np.empty((2,4))
print(emp)
print('\n')
print('identity matrix:')
ide=np.identity(4)
print(ide)
print("\n")
arr=np.arange(99)
print(arr)
print(arr.reshape(3,33))
print(arr.ravel())
print("\n")


np.random.seed(42)
print('random number generation:')